remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "catppuccin_mocha"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-remote-theme

title: TrueDotBin
description: I do stuff.